USE [master]
GO

/****** Object:  Database [Pharm]    Script Date: 01.05.2022 13:18:32 ******/
CREATE DATABASE [Pharm]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Pharm', FILENAME = N'/var/opt/mssql/data/Pharm.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Pharm_log', FILENAME = N'/var/opt/mssql/data/Pharm_log.ldf' , SIZE = 8192KB , MAXSIZE = 102400KB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Pharm].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Pharm] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Pharm] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Pharm] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Pharm] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Pharm] SET ARITHABORT OFF 
GO

ALTER DATABASE [Pharm] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Pharm] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Pharm] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Pharm] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Pharm] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Pharm] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Pharm] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Pharm] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Pharm] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Pharm] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Pharm] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Pharm] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Pharm] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Pharm] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Pharm] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Pharm] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Pharm] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Pharm] SET RECOVERY FULL 
GO

ALTER DATABASE [Pharm] SET  MULTI_USER 
GO

ALTER DATABASE [Pharm] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Pharm] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Pharm] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Pharm] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Pharm] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Pharm] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Pharm] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Pharm] SET  READ_WRITE 
GO

USE [Pharm]
GO
/****** Object:  Table [dbo].[ActiveSubstances]    Script Date: 01.05.2022 13:22:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ActiveSubstances](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](200) NOT NULL,
 CONSTRAINT [PK_ActiveSubstances] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Medications]    Script Date: 01.05.2022 13:22:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Medications](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[SubstanceId] [int] NOT NULL,
	[Name] [nvarchar](1000) NOT NULL,
	[Price] [decimal](18, 2) NOT NULL,
	[Quantity] [int] NOT NULL,
 CONSTRAINT [PK_Medications] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MedicationsChangeHistory]    Script Date: 01.05.2022 13:22:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MedicationsChangeHistory](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[MedicationId] [int] NOT NULL,
	[SourceChangeId] [int] NOT NULL,
	[Parameter] [nvarchar](50) NOT NULL,
	[ValueBefore] [nvarchar](1000) NULL,
	[ValueAfter] [nvarchar](1000) NULL,
	[Created] [datetime] NOT NULL,
 CONSTRAINT [PK_MedicationsChangeHistory] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Medications]  WITH CHECK ADD  CONSTRAINT [FK_Medications_ActiveSubstances] FOREIGN KEY([SubstanceId])
REFERENCES [dbo].[ActiveSubstances] ([Id])
GO
ALTER TABLE [dbo].[Medications] CHECK CONSTRAINT [FK_Medications_ActiveSubstances]
GO

